select 
    ITEM_TREE.ITEM_ID,
    ITEM_INFO.ITEM_NAME
from ITEM_TREE
inner join ITEM_INFO
    on ITEM_TREE.ITEM_ID = ITEM_INFO.ITEM_ID
where ITEM_TREE.PARENT_ITEM_ID is NULL
order by ITEM_TREE.ITEM_ID asc