SELECT BOARD.TITLE, BOARD.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, LEFT(REPLY.CREATED_DATE, 10) AS CREATED_DATE
FROM USED_GOODS_BOARD AS BOARD
JOIN USED_GOODS_REPLY AS REPLY ON BOARD.BOARD_ID=REPLY.BOARD_ID
WHERE SUBSTRING(BOARD.CREATED_DATE, 6,2)="10"
ORDER BY REPLY.CREATED_DATE ASC, BOARD.TITLE ASC;